// Module included in the following assemblies:
//
// * managing_cluster_configuration/managing-openshift-cluster-configuration.adoc

:_mod-docs-content-type: REFERENCE
[id="configuring-the-default-argocd-instance_{context}"]
= Configuring the default Argo CD instance

Though the Operator creates a default Argo CD instance in the openshift-gitops namespace, you must configure the instance to make it useful when deploying applications and setting cluster configuration. The configurations include:

* RBAC: Argo CD uses its own RBAC configuration and the default permissions configured by the Operator may not be sufficient depending on the OpenShift groups your user has been assigned.
* Permissions: The Operator configures the default instance with a default set of Kubernetes permissions but these are typically insufficient and additional privileges are required.


Although the Operator creates a default Argo CD instance in the openshift-gitops namespace, you must configure the instance to make it useful for deploying applications and setting cluster configuration. The configurations include:
* RBAC: Argo CD uses its own RBAC configuration. The default permissions configured by the Operator may not be sufficient, depending on the OpenShift groups your user has been assigned.
* Permissions: The Operator configures the default instance with a default set of Kubernetes permissions. However, these are typically insufficient, and additional privileges are required.